# Generated by Django 3.0.5 on 2020-10-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201007_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='Student',
        ),
    ]
